name: 'Push Homebrew Formula'
description: 'Generate and push Homebrew formulae to a tap repository from a template'

inputs:
  name:
    description: 'Project name (defaults to repository name)'
    required: false
  url:
    description: 'URL to the artifact (auto-discovered from GitHub release if omitted)'
    required: false
  sha256:
    description: 'SHA256 checksum of the artifact (auto-computed from url if omitted)'
    required: false
  version:
    description: 'Version string (defaults to current tag with v prefix stripped)'
    required: false
  tap:
    description: 'Target tap repository, e.g. owner/homebrew-tap'
    required: true
  tap-branch:
    description: 'Branch to push to in the tap repository'
    required: false
    default: 'main'
  versioned-path:
    description: 'Path for versioned formula in the tap, e.g. Formula/app@${VERSION}.rb'
    required: false
  latest-path:
    description: 'Path for latest formula in the tap, e.g. Formula/app.rb'
    required: true
  template:
    description: 'Path to the formula template file in the calling repository'
    required: true
  commit-message:
    description: 'Commit message (${VERSION} is replaced)'
    required: false
    default: 'Deploy Formula ${VERSION}'
  tap-token:
    description: 'PAT with push access to the tap repository'
    required: true
  committer-name:
    description: 'Git committer name'
    required: false
    default: 'github-actions[bot]'
  committer-email:
    description: 'Git committer email'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

outputs:
  version:
    description: 'The resolved version string'
    value: ${{ steps.run.outputs.version }}
  sha256:
    description: 'The resolved or computed SHA256'
    value: ${{ steps.run.outputs.sha256 }}

runs:
  using: 'composite'
  steps:
    - name: Cache Babashka
      id: cache-bb
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}/bin/bb
        key: bb-${{ runner.os }}-${{ runner.arch }}

    - name: Install Babashka
      if: steps.cache-bb.outputs.cache-hit != 'true'
      shell: bash
      run: bash <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install) --dir "${{ runner.temp }}/bin"

    - name: Install Homebrew
      uses: Homebrew/actions/setup-homebrew@main

    - name: Push Homebrew formula
      id: run
      shell: bash
      env:
        INPUT_NAME: ${{ inputs.name }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_SHA256: ${{ inputs.sha256 }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_TAP: ${{ inputs.tap }}
        INPUT_TAP_BRANCH: ${{ inputs.tap-branch }}
        INPUT_VERSIONED_PATH: ${{ inputs.versioned-path }}
        INPUT_LATEST_PATH: ${{ inputs.latest-path }}
        INPUT_TEMPLATE: ${{ inputs.template }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_TAP_TOKEN: ${{ inputs.tap-token }}
        INPUT_COMMITTER_NAME: ${{ inputs.committer-name }}
        INPUT_COMMITTER_EMAIL: ${{ inputs.committer-email }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        export PATH="${{ runner.temp }}/bin:$PATH"
        cd "${{ github.action_path }}"
        bb -m tap-push.core
